### ISSUE TITLE
Publish to Maven Central / JCenter

### ISSUE THREAD

**Issue by pron** [biboudis/jmh-profilers#2]
Great work!

**Comment by biboudis** [comment]
Haven't done it before. I am on it (sonatype).

**Comment by biboudis** [comment]
Hi @pron. the project is now on central / sonatype. I have put the dependency at the README file. 

Please test and tell me if you have any problems.

And again, if you have any ideas for more profilers plugins, the project is open for contributions.

**Comment by pron** [comment]
Great! I'll give it a try next week. Thank you!

**Comment by biboudis** [comment]
Ok. It works. I've just checked it as a scala sbt dependency.

Cheers.
