### ISSUE TITLE
Give JFR recording file meaningful names

### ISSUE THREAD

**Issue by pron** [biboudis/jmh-profilers#3]
Got around to playing with this finally. Very nice!
The produced recording files should be named in a way that makes it easy to match them to the appropriate benchmark.

**Comment by circlespainter** [comment]
We got default-named recordings while using it with JMH 1.6, the built-in runner and the following JFR `java` args:

```
-XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:FlightRecorderOptions=defaultrecording=true,dumponexit=true,settings=profile
```

It doesn't seem to happen when using the same args and JMH 1.3.1 though, so it might be a matter of compatibility with newer JMH versions.
